# Generated by Django 2.1.5 on 2019-02-09 16:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_photo', models.ImageField(blank=True, upload_to='students/%m/%d/')),
                ('student_collegeId', models.CharField(max_length=255)),
                ('student_emailId', models.EmailField(max_length=254)),
                ('student_aadharId', models.CharField(max_length=255)),
                ('student_fullname', models.CharField(max_length=1024)),
                ('student_contact', models.CharField(max_length=100)),
                ('student_dob', models.DateField()),
                ('student_year', models.CharField(choices=[('FE', 'First Year'), ('SE', 'Second Year'), ('TE', 'Third Year'), ('BE', 'Fourth Year')], max_length=20)),
                ('student_department', models.CharField(max_length=512)),
                ('student_address', models.TextField()),
                ('source_station', models.CharField(max_length=255)),
                ('destination_station', models.CharField(max_length=255)),
                ('train_class', models.CharField(choices=[('First', 'First Class'), ('Second', 'Second Class')], max_length=50)),
                ('isApproved_college', models.BooleanField(default=False)),
                ('application_date', models.DateTimeField(default=datetime.datetime(2019, 2, 9, 16, 26, 32, 140739, tzinfo=utc))),
            ],
        ),
    ]
