# Generated by Django 2.1.5 on 2019-02-09 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collegeApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeapplication',
            name='application_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 9, 17, 16, 29, 977826, tzinfo=utc)),
        ),
    ]
