# Generated by Django 2.1.5 on 2019-02-10 05:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collegeApplication', '0004_auto_20190210_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeapplication',
            name='application_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 10, 5, 38, 36, 448029, tzinfo=utc)),
        ),
    ]
