# Generated by Django 2.1.5 on 2019-02-10 05:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collegeApplication', '0006_auto_20190210_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeapplication',
            name='application_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 10, 5, 44, 59, 179412, tzinfo=utc)),
        ),
    ]
