# Generated by Django 2.1.5 on 2019-02-10 03:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('railwayApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railwayapplication',
            name='application_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 10, 3, 23, 22, 643684, tzinfo=utc)),
        ),
    ]
