# Generated by Django 2.1.5 on 2019-02-10 05:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('railwayApplication', '0004_auto_20190210_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railwayapplication',
            name='application_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 10, 5, 39, 1, 474949, tzinfo=utc)),
        ),
    ]
